#!/bin/sh

app_name_prefix="Airtel 4G"
# external version number
swVersion="PCM_ARTINDV1.0.1B04"
# internal version number
swRevision="PCM_ARTINDIIMF825AV1.0.1B04"
swRevisionDate="D20150513"
support_mac_autorun="YES"
support_languages="English.lproj"
cfgFiles=""
app_name="Airtel 4G.app"
app_root="/Applications"
drv_root="/System/Library/Extensions"
drv_names="ZTEUSBCDCACMData.kext ZTEUSBMassStorageFilter.kext"
pref_root="/System/Library/ModemList"
recp_root="/Library/Receipts"
inst_comps="app.pkg drv.pkg"
pkgDir="$1/Contents/Resources"
app_support_path="/Library/Application Support/DataCard Manager"
common_data_path="/usr/local/join_air_data"
update_app_path="/Library/Application Support/DataCardUpdater"
LaunchAgent_Path="/Library/LaunchAgents"
tmpDir="/private/tmp"


#drv info for get dev version
drvInfo_tmpDir="$tmpDir/drvInfo.plist"
src_drvpkg="$1/Contents/Packages/drv.pkg"

Need_Alias="NO"
Need_Dock="NO"
SetECMFirst="NO"
KEEP_ALIVE="NO"
cfgLogoOrIconFiles="icon.icns"
WebURL="http://m.home/"
WebLinkUrl=""
WebLinkFile="WebLink.app"
WebLinkDest="/Applications"

Need_BackUp="NO"
IsWebUI="NO"
MTK_Version="NO"
UseHostlessDaemon="NO"
# Swapper
Swapper_Config="/Library/LaunchAgents/DeviceMonitor.plist"

# PPPMonitord
PPPMonitord_Config="/Library/LaunchDaemons/PPPMonitor.plist"

dst_root="$app_root/$app_name/Contents/Resources"
src_root="$pkgDir/AutorunResource"

src_demon="$src_root/Mac_DeviceMonitor.app"
dst_demon="$app_support_path/Mac_DeviceMonitor.app"

src_profile="$src_root/swapper_monitor_profile.plist"
dst_profile="$pref_root/swapper_monitor_profile.plist"
dst_profile_domain="$pref_root/swapper_monitor_profile"

#old swapper &pppmonitor
Old_Swapper_Config="/Library/LaunchAgents/Swapper.plist"
Old_PPPMonitord_Config="/Library/LaunchDaemons/PPPMonitord.plist"
Old_app_support_path="/Library/Application Support/Join Air"

# Font
font_path="/Library/Fonts"
font_name=""

Is_Support_Languge()
{
	TEMP="$1"
	if [ "X$TEMP" = "X" ]; then
		return 1
	fi
       
	for STR1 in $support_languages; do
	
		if [ "X$STR1" =  "X$TEMP" ]; then
			return 0
		fi
	
	done

	return 1
}

