#!/bin/sh

source "$1/Contents/Resources/common"
app_res="$app_root/$app_name/Contents/Resources"
updater_path="$app_res/CMUpdater.app"

if [ -e "$app_res/ArchiveRes.7z" ]; then
	unzip -o "$app_res/7za.zip" -d "$app_res"
	"$app_res/7za" x "$app_res/ArchiveRes.7z" -y -o"$app_res"
	mv -f "$app_res/ArchiveRes/Frameworks" "$app_res/ArchiveRes/PlugIns" "$app_root/$app_name/Contents"
	cp -Rf "$app_res/ArchiveRes/" "$app_res"
	rm -Rf "$app_res/7za.zip" "$app_res/7za" "$app_res/ArchiveRes" "$app_res/ArchiveRes.7z"
fi

if [ -e "$app_res/Custom_Resources" ]; then
	cp -Rf "$app_res/Custom_Resources/" "$app_res"
	rm -Rf "$app_res/Custom_Resources"
fi


chmod -R 0755 "$app_root/$app_name/Contents/Frameworks" "$app_root/$app_name/Contents/PlugIns"
chmod -R 0777 "$app_res"


echo "exfight finished"
