#!/bin/sh

# preflight.sh
# dataCard
#
# Created by raoyuanjie on 8/29/07.
# Copyright 2007 __MyCompanyName__. All rights reserved
  
source "$1/Contents/Resources/common"
 
 #
 #when install Mac_DeviceMonitor ,we have to unload the previous Mac_DeviceMonitor,
 #in order to install the new app, if we don't do this ,the new UI will start before the installation is finished
 #
 if [ -f "$Swapper_Config" ]; then
 su -l "$USER" -c "launchctl unload -S Aqua $Swapper_Config"
 fi
echo >> /dev/null