#!/bin/sh

source "$1/Contents/Resources/common"

Uninstall_Driver_Script="$1/Contents/Packages/drv.pkg/Contents/Resources/UninstallDatacardDriver"

SEARCH_RESULT=$(echo $app_name_prefix | grep /)	# Search /
if [ "x$SEARCH_RESULT" != "x" ]; then
	APP_FOLDER_NAME="${app_name_prefix%/*}"
else
	APP_FOLDER_NAME=""
fi
APP_NAME_PREF="${app_name_prefix##*/}"

Uninstall_File="$app_root/Uninstall $APP_NAME_PREF.app"
Uninstall_FileName="Uninstall $APP_NAME_PREF"

if ! [ -e "/private/tmp" ]; then
	mkdir "/private/tmp"
fi
cp -R "$1/Contents/Resources/Uninstall/Uninstall.app" "/private/tmp"
cp "$dst_root/icon.icns" "/private/tmp/Uninstall.app/Contents/Resources/"
mv "/private/tmp/Uninstall.app" "$Uninstall_File"
if [ ! -e "$Uninstall_File" ]; then
	echo "########## \"$Uninstall_File\" is invalid ##########"
	exit 1
fi

#defaults write "$Uninstall_File/Contents/Info" CFBundleName -string "$Uninstall_FileName"

# copy comoon to UI Resource
cp "$1/Contents/Resources/common" "$Uninstall_File/Contents/Resources/"
cp -R "$pkgDir/BackupAndRestore.app" "$Uninstall_File/Contents/Resources/BackupAndRestore.app"
# Copy uninstall script to uninstall from drv.pkg
if [ -e "$Uninstall_Driver_Script" ]; then
	cp "$Uninstall_Driver_Script" "$Uninstall_File/Contents/Resources/"
else
	echo "########## Driver uninstall script is invalid ##########"
#	exit 1
fi

# LinkOperation
if [ "x$Need_Alias" = "xYES" ]; then
	cp -R "$pkgDir/LinkOperation.app" "$Uninstall_File/Contents/Resources"
	if [ -e "$Uninstall_File/Contents/Resources/LinkOperation.app/Contents/Resources/Config.plist" ]; then
		defaults write "$Uninstall_File/Contents/Resources/LinkOperation.app/Contents/Resources/Config"  "SourceFile" -string "$app_root/$app_name"
		defaults write "$Uninstall_File/Contents/Resources/LinkOperation.app/Contents/Resources/Config"  "UserHome" -string "$HOME"
		"$Uninstall_File/Contents/Resources/LinkOperation.app/Contents/MacOS/LinkOperation" -a
	fi
fi

# Add to Dock
if [ "x$Need_Dock" = "xYES" ]; then
	ADD_DOCK_PATH="$Uninstall_File/Contents/Resources/AddIntoDock.app"
	DEL_DOCK_PATH="$Uninstall_File/Contents/Resources/DelFromDock.app"
	if [ -e "$ADD_DOCK_PATH" ]; then
		mv "$ADD_DOCK_PATH/Contents/Resources/AppPreference" "$ADD_DOCK_PATH/Contents/Resources/AppPreference.plist"
		defaults write "$ADD_DOCK_PATH/Contents/Resources/AppPreference" "AppFullPath" -string "$app_root/$app_name/"
		defaults write "$ADD_DOCK_PATH/Contents/Resources/AppPreference" "AppName" -string "$APP_NAME_PREF"
		chown root:admin "$ADD_DOCK_PATH/Contents/Resources/AppPreference.plist"
		chmod 0664 "$ADD_DOCK_PATH/Contents/Resources/AppPreference.plist"
		mv "$ADD_DOCK_PATH/Contents/Resources/AppPreference.plist" "$ADD_DOCK_PATH/Contents/Resources/AppPreference"
	fi
	if [ -e "$DEL_DOCK_PATH" ]; then
		mv "$DEL_DOCK_PATH/Contents/Resources/AppPreference" "$DEL_DOCK_PATH/Contents/Resources/AppPreference.plist"
		defaults write "$DEL_DOCK_PATH/Contents/Resources/AppPreference" "AppFullPath" -string "$app_root/$app_name/"
		defaults write "$DEL_DOCK_PATH/Contents/Resources/AppPreference" "AppName" -string "$APP_NAME_PREF"
		chown root:admin "$DEL_DOCK_PATH/Contents/Resources/AppPreference.plist"
		chmod 0664 "$DEL_DOCK_PATH/Contents/Resources/AppPreference.plist"
		mv "$DEL_DOCK_PATH/Contents/Resources/AppPreference.plist" "$DEL_DOCK_PATH/Contents/Resources/AppPreference"
	fi
	open "$ADD_DOCK_PATH"
fi

# Web link operation
if [ "${WebLinkUrl}" != "" ] && [ "${WebLinkFile}" != "" ] && [ -d "$WebLinkDest" ]; then
	if [ -e "$pkgDir/$WebLinkFile" ]; then
		cp -R "$pkgDir/$WebLinkFile" "$WebLinkDest"
		defaults write "$WebLinkDest/$WebLinkFile/Contents/Info" WebURL -string "$WebLinkUrl"
		chown -R root:admin "$WebLinkDest/$WebLinkFile"
		chmod -R 0775 "$WebLinkDest/$WebLinkFile"
		
		cp -R "$pkgDir/LinkOperation.app" "$Uninstall_File/Contents/Resources/LinkOperationWeb.app"
		if [ -e "$Uninstall_File/Contents/Resources/LinkOperationWeb.app/Contents/Resources/Config.plist" ]; then
			defaults write "$Uninstall_File/Contents/Resources/LinkOperationWeb.app/Contents/Resources/Config"  "SourceFile" -string "$WebLinkDest/$WebLinkFile"
			defaults write "$Uninstall_File/Contents/Resources/LinkOperationWeb.app/Contents/Resources/Config"  "UserHome" -string "$HOME"
			"$Uninstall_File/Contents/Resources/LinkOperationWeb.app/Contents/MacOS/LinkOperation" -a
		fi
		
		# make uninstall
		echo "" >> "$Uninstall_File/Contents/Resources/Uninstall_Up"
		echo "\"$Uninstall_File/Contents/Resources/LinkOperationWeb.app/Contents/MacOS/LinkOperation\" -d" >> "$Uninstall_File/Contents/Resources/Uninstall_Up"

		echo "" >> "$Uninstall_File/Contents/Resources/Uninstall_Low"
		echo "if [ -e \"$WebLinkDest/$WebLinkFile\" ]; then" >> "$Uninstall_File/Contents/Resources/Uninstall_Low"
		echo "	rm -Rf \"$WebLinkDest/$WebLinkFile\"" >> "$Uninstall_File/Contents/Resources/Uninstall_Low"
		echo "fi" >> "$Uninstall_File/Contents/Resources/Uninstall_Low"
	fi
fi

# Set uninstall app
chown -R root:admin "$Uninstall_File"
chmod -R 0775 "$Uninstall_File"